import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTop from "./ui/scrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DeviPothula Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col mx-[30px] mt-[40px]`}
      >
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
